import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/componentes/Navbar";
import NavbarImage from "@/componentes/NavbarImage";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aplicacion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className=" bg-orange-200/30 ">
      <body className={inter.className}>
        
        {children}
      </body>
    </html>
  );
}
